### ISSUE TITLE
I18n documentation is missing

### ISSUE THREAD

**Issue by iwiznia** [pluginaweek/state_machine#114]
I don't see how to congifure the I18n, digging in the code, I saw that for the activerecord integration it looks for activerecord.state_machines.[model_name].[state_machine_name].states and .events
Although there are some things that I can't get translated correctly, precisly the InvalidTransition message, no matter how I configure it, it doesn't translate the "value" param.
Am I missing something? It's just a documentation bug or there's a bug with the translations?

**Comment by obrie** [comment]
Thanks for taking the time to report this issue.  There aren't any known issues with regard to using i18n currently.  To fully understand where you're seeing the issue, I'll need to know:
- What version of Ruby are you running?
- What ORM are you using (ActiveRecord, Mongoid, etc.)?
- What web framework are you running (Rails, Sinatra, etc.)?
- What does your i18n configuration look like?

I can tell you that i18n appears to work on Ruby 1.8.7 / Rails 3 / ActiveRecord using the following examples:

config/locales/en.yml

``` yaml
en:
  activerecord:
    errors:
      messages:
        invalid: "is unknown"
        invalid_event: "cannot run the transition when %{state}"
        invalid_transition: "cannot run the transition via %{event}"
    state_machines:
      states:
        parked: "stopped"
      events:
        park: "stop"
```

app/models/user.rb

``` ruby
class User < ActiveRecord::Base
  state_machine :initial => :parked do
    event :park do
      transition :idling => :parked
    end
  end
end
```

``` ruby
u = User.new                # => #<User id: nil, name: nil, state: "parked", created_at: nil, updated_at: nil, deleted_at: nil> 
u.park                      # => false 
u.errors                    # => #<OrderedHash {:state=>["cannot run the transition via stop"]}> 
u.state_event = "shift_up"  # => "shift_up" 
u.valid?                    # => false 
u.errors                    # => #<OrderedHash {:state_event=>["is unknown"]}> 
u.state_event = "park"      # => "park" 
u.valid?                    # => false 
u.errors                    # => #<OrderedHash {:state_event=>["cannot run the transition when stopped"]}> 
```

Let me know if this helps or if I'm testing with the wrong configuration.

**Comment by iwiznia** [comment]
- Ruby version: 1.8.7
- ORM: ActiveRecord.
- Framework: Rails 2.3.10
  My I18n looks like this:

```
es:
  activerecord:
    state_machines:
      stateful_model:
        state:
          state1: State 1
          state2: State 2
        events:
          event1: Event 1
          event2: Event 2
    errors:
      models:
        stateful_model:
          attributes:
            state:
              invalid_transition: "Can't change state from %{value} via %{event}"
```

The thing is that when the invalid_transition validation is fired, the value and event aren't translated using the translations given in "state" and "events" configs.

**Comment by obrie** [comment]
Thanks for following up.  There were a few issues at play here.  First, your locale definition wasn't structured quite right.  The translations for each individual state should be under a "states" key, not "state".  In addition, the "states" and "events" keys need to be under a "state" key (representing the name of your machine).  The second problem is that "%{value}" always represents the actual value of the attribute for the validation error.  It doesn't get converted to the human name.

So the immediate change you can do is update the structure of your locale like so:

```
es:
  activerecord:
    state_machines:
      stateful_model:
        state:
          states:
            state1: State 1
            state2: State 2
          events:
            event1: Event 1
            event2: Event 2
    errors:
      models:
        stateful_model:
          attributes:
            state:
              invalid_transition: "Can't change state from %{value} via %{event}"
```

Now, there are 2 changes I've made in master that haven't been released yet.  The first is that you can now define the "states" and "events" translations under the "stateful_model" key instead of requiring an additional nesting under the "state" key (the name of your machine).

The other change is that the "invalid_transition" translation now supports an interpolation for "%{state}" which represents the human name of the current state.

In addition, I've taken note to improve the docs a bit.

Hope all of this helps!
